### ISSUE TITLE
Replace fancy_vend

### ISSUE THREAD

**Issue by ChandlerBing1994** [Craigs-Crew/edgy-dark-ominous-game#42]
Not that good imo, I believe it should be replaced with EasyVend.

**Comment by bobmacphee** [comment]
Definitely replace in my opinion, I never found it to be particularly good on Craig's (for the short while that we did experiment with it) and I think the big crosses it shows when it's out of stock are highly unattractive. Personally I would rather see the use of the far less laggy easyvend mod which has a clear stock indicator on the front, and makes use of a chest below the shop for stock. The shops in Craig's were always a pain to reload because you couldn't shift-click and there wasn't enough space in them. https://forum.minetest.net/viewtopic.php?t=15472

**Comment by lumberjackgames** [comment]
Agree to replace

**Comment by lisacvuk** [comment]
easyvend +1
