### ISSUE TITLE
Merge smelting/furnace with workbench

### ISSUE THREAD

**Issue by lisacvuk** [Craigs-Crew/edgy-dark-ominous-game#47]
Smelting causes lag and often feels annoying - on the other side, it adds a cost to making some materials. Perhaps we can have furnaces directly craft Input + Fuel into Output? With the ability to craft full stacks at a time, this should keep the cost element, but get rid of the lag.

**Comment by lumberjackgames** [comment]
I support a furnace crafting station. I definitely prefer instacraft over server lag, but a couple things come to mind that I think are worth talking through
- **Lack of furnace animation:** Personally I feel like some postive ambience to the game will be lost without an animated furnace block. burning and working away add a nice warm glow when you are playing. That would be lost if we simply do away with smelting having a time cost altogether. 

Perhaps we could consider a short fixed time cost (reglardless of stack or single item) with a brief animation, instead of a per item time cost (O(n)) could be a happy a compromise? For example, what if a stack and an item had the same cook time?

Just a thought. I won't fight back if I'm the only one that thinks something positive is lost by removing a time element from smelting, but I think its worth considering how it impacts the gameplay and ambience of the game. There is a bit of fun to having multiple furnaces going and multitasking during crafting sessions, but I definitely agree its a good idea to streamline smelting and define limits to the lag it can cause.

**Comment by wrynvera** [comment]
I agree with the appeal of the animations.

This could potentially be combined with the workstations idea in #45 
Namely. the furnace will now function as a workstation.
It will still require fuel to run, once its active/running, the cooking tab will be accessible accordingly, allowing instant crafting of cooking recipes.
This can be expanded further in cost, having more different smelting stations, like blast furnaces, ovens etc.
This appeals to both the animations + instant crafting, while still relying on a certain fuel cost.

With the fact that the furnace is now just a fuel consuming node, it cuts down a lot of the code as well, and should aid in the lag-reduction.

**Comment by lumberjackgames** [comment]
> It will still require fuel to run, once its active/running, the cooking tab will be accessible accordingly, allowing instant crafting of cooking recipes.

Generally, how will this be implemented without the same problems (time checks on remaining fuel) that current furnace has? Are you saying leave the fuel checks but then remove the need to check cooktime/expiration?

I think that may be a nice compromise and probably cut out a lot of the risk of lag the current implementation has.

**Comment by wrynvera** [comment]
When the fuel is running, the furnace is swap into a different node (active node) as per currently.
The workbench will simply detect for that.

Yes cooktime is cut entirely, cooked items are instantly crafted as long as the furnace is active.

**Comment by ChandlerBing1994** [comment]
Agreed with neinwhal.

**Comment by wrynvera** [comment]
Approval from @theraven262 on discord.
I'll close this and merge further information with the WIP workbench thread #45
