### ISSUE TITLE
Remove cobble drop from stone nodes

### ISSUE THREAD

**Issue by lumberjackgames** [Craigs-Crew/edgy-dark-ominous-game#55]
Dealing with cobble is annoying and having to smelt it is just tedious, imo. Dealing with ores is enough work.

I think there should be a grinder craft station that handles taking stone/sandstone (whatever material we want) down to cobble/gravel/sand and if we want to be able to recombine them somehow we can work out another craft station for that (compactor?)

Alternatively, higher rated tools don't drop cobble.

Just wanted to float the idea out and see how other people feel.

**Comment by theraven262** [comment]
Agreed, since we making it a building server, why not. Gravel, cobble, sand could all be made from stone in some kind of a grinder tool.

**Comment by ChandlerBing1994** [comment]
Agreed, per Raven.

**Comment by wrynvera** [comment]
Disagree.
Two reasons.
1. With my workbench change, smelting items can be done near instantaneously, decreasing the wait for smelting stone.
2. I don't want to break this natural order of things. To me, it just feels weird getting stone instead of cobble.

If (1) isn't enough reason to justify,  I would rather higher-rated tools don't drop cobble. Could be an alternative use for the mithril pickaxe.
I like the crafting aspect in getting blocks.
While certain blocks are too hard, stone definitely isn't one of it, and I don't want to simplify it further just for the sake of it.

I want to appeal again to the survival aspect.
In particular, the definition i defined in my workbench thread;
> certain stage of progression to the crafting, rather than opening up everything to the player at once.

There should still maintain a certain aspect of difficulty in gathering resources, otherwise we might as well jump into creative.
I feel that making this change, personally, is a step too far.

**Comment by ChandlerBing1994** [comment]
Completely forgot about the changes done to smelting. I agree with neinwhal.

**Comment by wrynvera** [comment]
Had a discussion with lumber on discord. I will summarize the points as per here for concerns on both sides.
For changing drop to stone: (lumber)

- Process of changing cobble to stone is tedious and unnecessary step
- Asymmetry of having some nodes drop cobble while most other mods skipping this step

Against changing drop to stone: (me)

- My benchwork-furnace change simplifies the process by a ton, you can craft stacks of stone in seconds, I don't think the process will be a concern anymore.
- Making stone the new "cobble", will make it a trash node (you will definitely get too much cobble from mining and have to trash some), personally, my love for stone is too much for it to replace cobble as the new trash node;
- ^ Following above: Retaining cobble as the trash node

**Comment by theraven262** [comment]
Alright, I agree we should keep the stone > cobble drops, but would still like if there was a grinder node that converts it into gravel and sand (maybe other sand types as well?).

**Comment by lumberjackgames** [comment]
Going to wait and see how the new furnace mechanics work and feel, then we can look at possibly adding support for digging stone directly with a mithril pick or other special tool later if needed, but this is non-essential for now.

If there is interest in a grinder, let's start a new issue for that, as well.
