### ISSUE TITLE
Map boundary limitation for future expansion

### ISSUE THREAD

**Issue by theraven262** [Craigs-Crew/edgy-dark-ominous-game#56]
Since we can not add more ores after the release (without them appearing only in new chunks), maybe we should limit the map depth/height for now, so we can add more new ores later on.

**Comment by lumberjackgames** [comment]
We could easily implement this at the server level. Not sure if we want to add something like worldlimit as a part of the game for some built in respawning management. Could be useful.

Generally speaking, I support this as a good idea also just to slow the growth of the map somewhat for storage reasons. I think its good to start with limits to future proof the map in case any "got to have" feature pop up that we want to add. 

It probably goes without saying, but we should think through our ore/decoration selection as much as possible before starting a permanent map and try come to a place where we are happy with the selection of things and won't need to disrupt the stability of the map stuff anymore than necessary.

**Comment by wrynvera** [comment]
As of recent changes to the server, I have added a script to delete existing map blocks.

This would be the ideal way for managing the map size.

Realistically, at the current point, my server can only support up till 30GB, excluding some extra space for my personal stuff.
This space is expandable at the rate of USD$1/10GB, but unless there's a steady stream of donations, I'm not keen of intentionally expanding that.

Map size limit should be kept under this logic as well. Ideally, the limits I am thinking of is 10k width (so -5000 to 5000) and 16k height (-5000 to 11000), the latter is due to the spawn build.
EDIT (from discussion on comment below): height to be limited to be from (-10000 to 4000), spawn build to be moved to 3k, lower limit to be further determined upon completion of new cave changes.

While players can explore, build and gather outside of these limits, those areas will be reset and hence progress will be lost upon every restart.
This is potentially a positive too, since it offers a region of semi-renewable resources.

I'm not really sure how much 30GB entails, so 10k seems to be a safe limit but requires more testing. Ideally, this limit should be kept under 25GB, with 5GB serving as extra space to accommodate for the temporary exploration.

**Comment by theraven262** [comment]
I'm against setting the upper limit to 11000 just because we decided that the spawn ship should be exactly 10000 nodes above the sea level. That is a lot of wasted space.
I have planned 8000 depth for the underground and since we're adding a lot of underground content I believe that this is a reasonable depth. Could we lower the spawn somewhat to cover this? We really won't ever need to expand below -8000 by my plan.
As per the horizontal limits, as you said it might actually be a good thing to limit the map persistence. And I think 5000 in all directions is very much enough for building, if nothing else at least for the first couple of years.

**Comment by wrynvera** [comment]
Issue discussion transferred to discord for consistency
