### ISSUE TITLE
Areas & markers: Discussion on means of node protection

### ISSUE THREAD

**Issue by lisacvuk** [Craigs-Crew/edgy-dark-ominous-game#6]
There has been discussion on Discord about splitting the world into chunks that can be purchased by players - this would make the areas mod redundant.

**Comment by lumberjackgames** [comment]
the big disadvantage to getting rid of areas is nice administrative options for like blocking off big chunks add/granting access. There are more minimal protection mods that offer block by block protection. I think if protection is built into the game, and it is to be block by block (easiest for managing purchase--otherwise would be by the node) then we should look at https://github.com/SmallJoker/simple_protection as a starting point.

It's possible the mods aren't mutually exclusive and we could leave areas as an option on the server without including it as essential to the game. For example simple protection handles the buy/sell protection and as a mod use areas as server implementation only for administrative/special purposes.

**Comment by wrynvera** [comment]
I have been working on a protection mod, similar to what smalljoker has, a fixed grid protection, that uses even a simpler system.
But at the same time, I do see the benefit of areas mod, because it can protection non-flexible areas.

My suggestion, is that we can potentially have both.
My mod i referenced above, already kinda of does that, adding support for areas.

**Comment by ChandlerBing1994** [comment]
I think the current area protection mod is fine, however we'll need to protect roads as well, and unfortunately the roads waste area numbers making things more cluttered than they should be. Perhaps modify it a bit so that if an area is protected as [ROAD] by an admin it's saved as its own separate thing.

**Comment by lisacvuk** [comment]
Something like this, maybe? https://imgur.com/1kGWUNr.png  
It would be unique (i think) and it would be much easier for new players to manage.  
There would be no problems with roads going through existing builds, too.

**Comment by ChandlerBing1994** [comment]
Could you elaborate a bit further? I'm not sure I understand that plan.

**Comment by lisacvuk** [comment]
When the map is generated, it's split into protected blocks. These are all owned by the server. Between these blocks are the road reservations, also owned by the server, but with a selected few players able to build in them. A player can use a node or a command or a tool to buy one of these blocks, for whatever currency we have.

**Comment by lisacvuk** [comment]
As for spawn/other areas of public interest, we can either follow the grid, or merge multiple of these blocks together. Perhaps allow players to claim the reserved road part if a road isn't built yet + they own both sides of it?

**Comment by lumberjackgames** [comment]
Areas also becomes a lag monster with many areas, at least it has been in the past. maybe the new db implementations fix this though

**Comment by lumberjackgames** [comment]
> As for spawn/other areas of public interest, we can either follow the grid, or merge multiple of these blocks together. Perhaps allow players to claim the reserved road part if a road isn't built yet + they own both sides of it?

A way to automatically add area owners to nearby areas classified as a "road areas" group would be really nice.

Edit: on second thought that will probably be abused but there should be a way to whitelist/blacklist certain players for this ability

**Comment by ChandlerBing1994** [comment]
I'm in support of the idea if it's not too strict. Too strict in this case would be preventing regular users from making megabuilds.

**Comment by wrynvera** [comment]
I think the implementation of it is something that has a lot more to discuss on, so this issue should focus on the decision of whether we should (1) rewrite areas, (2) retain areas, or (3) retain areas but provide another mod that works in conjunction.

Before we proceed to the stage where there is a taker to actually work on this and provide more concrete ideas, i think we should clarify the above.
Personally, I'm leaning towards 3. Areas is a massively complex mod and it does well for what it proposes to do, I don't think its worthwhile reinvesting it, but rather we should supplement it.

**Comment by lisacvuk** [comment]
> I'm in support of the idea if it's not too strict. Too strict in this case would be preventing regular users from making megabuilds.
  
If someone intends to make a megabuild but a road is already built between their areas, they should be able to contact the admins for a resolution. I don't think this will come up that often.  


> I think the implementation of it is something that has a lot more to discuss on, so this issue should focus on the decision of whether we should (1) rewrite areas, (2) retain areas, or (3) retain areas but provide another mod that works in conjunction.

I don't think we need a great deal of areas functionality.  

> Areas is a massively complex mod and it does well for what it proposes to do, I don't think its worthwhile rewriting it, but rather supplement it.  

I feel this used to be the case before MT got protection support in it's API. Nowadays, it should be relatively easy to implement a protection mod with https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L5989

**Comment by ChandlerBing1994** [comment]
> I think the implementation of it is something that has a lot more to discuss on, so this issue should focus on the decision of whether we should (1) rewrite areas, (2) retain areas, or (3) retain areas but provide another mod that works in conjunction.
> 
> Before we proceed to the stage where there is a taker to actually work on this and provide more concrete ideas, i think we should clarify the above. Personally, I'm leaning towards 3. Areas is a massively complex mod and it does well for what it proposes to do, I don't think its worthwhile reinvesting it, but rather we should supplement it.

I'm leaning towards three as well.

**Comment by wrynvera** [comment]
> I feel this used to be the case before MT got protection support in it's API. Nowadays, it should be relatively easy to implement a protection mod with https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L5989

It is simple, i agree, but the hard part is having a visual database of these areas.
That is something that areas itself does well, and is the complex part I'm referring to.

**Comment by lisacvuk** [comment]
Perhaps we should consider having a web interface for area management? Something along the lines of minetestmapper with an area grid overlaid, showing which areas are owned? In combination with an in-game way to see who owns the current area, of course. I realize that a web interface would be quite complex and likely outside of this projects scope - it would be cool, though :)

**Comment by lumberjackgames** [comment]
I think areas should be used in the proposed server implementation modpack repo, and we should consider a more simple option to include in game if we want a pay per block/chunk protecton mod.

To clarify I don't think using areas rewriting areas as a core mod of the game is worthwhile.

**Comment by bobmacphee** [comment]
One thing that I think is very important to maintain is flexibility in protecting areas, I hate the idea of fixed grids in general, the reason Craig's was quirky was because the roads and builds mostly followed the terrain. If you build everything in a perfect grid it just looks fake/world edited. 
I personally find the current areas mod quite adequate and think it's also important to have the 'open area' function. Definitely roads should have a different solution for protection to avoid different people 'owning' different bits of road and cluttering the protection list. I agree with proposal 3.

**Comment by wrynvera** [comment]
Not contributing to the main discussion, but I thought I should point out that I fully agree with bob regarding the grids.
While grids make sense in a proper city or so, I don't want to fit the entire server with that.
There should preferably be countrysides or wilderness, or even cities with flexible non-square grids, as per real life.
In particular, the application of grids to be limited to only a few proper city areas.

**Comment by lumberjackgames** [comment]
> If you build everything in a perfect grid it just looks fake/world edited.

fixed protection grids != building in perfect grids

I also don't think we need to micromanage how roads are built/protected as a core function of this game personally. This can be left to server operators' discretion (ie use areas on the server to protect roads where needed). I tried to solve this problem with city-states and it opens more cans of worms than I think the scope of this minimal building game should try to deal with.

EDIT: Just wanted to add that I know a grid protection system will probably lead to some tricky purchasing decisions when developing areas, but I think that is the appeal and maybe one of the few areas where this game has the potential to be "challenging" on some level.

**Comment by bobmacphee** [comment]
> fixed protection grids != building in perfect grids

Thank you for clarifying this, can you elaborate on fixed protection grids? Does this only allow the user to protect a fixed size/shape of area?

**Comment by lumberjackgames** [comment]
So the idea basically, is to make economy meaningful and cut out crap protected areas by having chunks of map to be protected at cost. Size/price and all the details are up for discussion. I think we should give a certain number of freebies, but just overall help cut down on the need for human administration of area protection is the biggest bonus, imo. If we did something like this, it should be compatible with using areas optionally as an additional mod for administrative purposes. 

Edit: a requirement is also to easily add/remove builders to your owned chunks and having a system for transferring ownership

**Comment by wrynvera** [comment]
> fixed protection grids != building in perfect grids

Just to reclarify my comment on grids, I do not mean the above with my comment.
As previously stated, I support the idea of grid protection, I just thought I should mention that in regards to building in perfect grids, because there were a few mentions of that above, to being one of the incentives to introduce the protection grid system, which is an idea I do not approve.

To answer bob's question also;
A protection grid basically divides the world into a grid, each of a fixed cell size.

**Comment by lisacvuk** [comment]
Perhaps just have normal areas mod, but make it cost a certain amount of gold per node to protect new areas? That way, players are encouraged to keep their protected areas as small as possible, and as few as possible, giving us less area clutter and area reservation  
  
Edit: Something that isn't too much, with 100x100x100 area being ~1 gold ingot, maybe?

**Comment by bobmacphee** [comment]
Thank you for the clarification gents, I do not approve of grid protection because no matter how you incorporate it, it will inevitably encourage players to get the maximum use out of their grid, they will build walls around it and fill it out as much as possible, which ultimately lead to people building in perfect grids. It also means that there will be massive areas of land with nothing on them because nooby players will build a tiny shack in one corner and leave the rest blank. 

Edit: I believe SG tried to incorporate something similar to this on Craig's whereby he sold/gave away blank 'postage stamps' of land, and nooby players did as I previously stated.

**Comment by wrynvera** [comment]
I think we should compare the advantages and disadvantages of each system.

Areas:
- Flexible protection
BUT
- Hard to use/understand for new players
- Possible gap areas that might be too small to utilize

Grid:
- No gaps, protection will be divided cleanly
- Easy to use/understand for new players
BUT
- Inflexibility 
- Potential to force the player to build in a grid system

There was a mention of economy being a benefit to the grid system by @lumberjackgames 
Areas could create one too, it is just that it's something that hasn't been implemented, as per building onto what @lisacvuk said above.

**Comment by lumberjackgames** [comment]
> Potential to force the player to build in a grid system

I can think of several ways this is easy to avoid. If you get say 5 free squares you can arrange them how you like. You should be rewarded for building, imo (not mining). Trade is optional to increase your earning rate. By the time you build enough to reasonably fill/manicure your protected areas, you will have earned enough to buy more areas that can be where ever you want. 

You can also cooperate to protect larger areas, share ownership, sell and trade areas strategically.

Nothing about this forces anyone to build any certain way. If anything it should make nooby players and map cleanup less of an issue if implemented correctly and chunks are not too large or costly.

**Comment by lumberjackgames** [comment]
If we were to use areas/area-markers in game these are some issues I think we would have to address:
- Area markers polluting map--possibly requiring nodetimers or abms to fix
- Shared owners deleting areas protection without notifying original owner
- Any case that ends up requiring admin intervention to make whatever permitted protection happen for normal players (such as protecting a tall area without fly privs) needs to be eliminated.

**Comment by wrynvera** [comment]
> I can think of several ways this is easy to avoid.

I initially wanted to add that in my thread on it.
But I reconsidered, and at the end of the day, a grid system is still forcing the playing to build within the limits of a fixed grid.
It doesn't have the flexibility that areas provide.
And if we are using smaller grids to try to solve that issue, protection management will be a pain, considering changing the access rights on 5 different protection blocks than a single one through areas.

> You can also cooperate to protect larger areas, share ownership, sell and trade areas strategically.

Areas can accomplish the same effect, if we apply a system similar to what lisac is suggesting.

As stated above, I'm pushing for (3).
I want areas' flexibility to be provided to the players who are trusted (and/or possibly; rich enough)
And for those that are not, the grid system is available.
Both system can make use of the economy and will work alongside each other. Areas in particular can overlap over existing grids, as long as the protecter own those grids.

**Comment by lumberjackgames** [comment]
The difference is the ability to protect rectangular areas of any size vs fixed square areas. The problems of building in fixed protected grids are implementation details not differences between the mods in my view. 

We are also skirting the long term costs of using areas, that it can lead to unlimited number of data points. I want to build this game for permanence over flexibility, personally. 

Again I"m totally fine with areas on the back end, and even no built-in area protection mod. Just don't think areas is a good choice for a base game...ever :)

**Comment by wrynvera** [comment]
> We are also skirting the long term costs of using areas, that it can lead to unlimited number of data points.

Unless the idea is that the grid system function in a local sort of way; which means that these protections can't be edited remotely, a grid system will eventually lead to a chunk of data as well.
But I can agree with that fact, that that will still be less data than areas, considering how more flexible areas is.

> Again I"m totally fine with areas on the back end

I think I can partially agree, we can build the grid system to be something that is a base, but supports areas.
But I like to see it to be something that is interacting with areas, rather than supporting.

**Comment by lumberjackgames** [comment]
> But I like to see it to be something that is interacting with areas, rather than supporting.

I am really concerned with how fast the scope of this game is growing overall. Almost every issue is closing with major rewriting of mods which impact either the map or core mechanics of the game. Several mods are being (re)written from scratch. Eluding to my previous comment about broken things in areas. If we need that granular of flexibility in protection, I'd rather use areas as is on the backend than in the base game for now. This may become a base for other games and I don't think we should impose that mod on the game itself. 

For me, implementing a whole grid system that is just a skin on areas is not a good use of time right now really. We can take time to think through a better UI and economic integration and implement that later when the core functionality of the game is done. 

As for implementation, if we are using areas then at a minimum we just need a really simple way for common players to just protect a square area from a cornerstone or something. I will refuse to help anyone with area protection and its just a labor sink for server admins.

Anyone that wants to have custom areas needs to have the ability to use the mod and the privs/ability to carry out that protection without admin intervention.

If we use area markers, the markers need to be removed automatically within a reasonable time after being placed but allowing time to store the area and remove the markers to save for later use if desired. 5 minute nodetimers may not be too much tax on the server.

**Comment by wrynvera** [comment]
> I am really concerned with how fast the scope of this game is growing overall.

I can agree with this; which is why i started #44 
I think this can fall into that category as well.
It is a low priority and work should be focus on more high priority things.
But I don't want to stop discussion on this, since I feel there's been quite a constructive one so far.

**Comment by ChandlerBing1994** [comment]
After thinking about it harder, I disagree with grids as they make things feel too robotic. Best solution imo at this point would just keep the current areas mod and add an extension to it that allows a "Road:" separated from the "Area:" option.

**Comment by lisacvuk** [comment]
I support areas with the following features, then:  
- Ability to /protect_road, which adds the selected area to a 0 ID (maybe) area called road
- Define a roadbuilder priv that allows people to build in the road area

**Comment by ChandlerBing1994** [comment]
Yup, though road IDs should be counted separately. Don't keep em all at 0, otherwise if someone makes a road that we later have to demolish that may cause issues.

**Comment by lisacvuk** [comment]
Yeah, i have no idea how we would handle unprotecting roads

**Comment by ChandlerBing1994** [comment]
Road IDs can also be kept hidden from regular players to prevent cluttering at the bottom left of the screen, the only ones who should be able to see them should be admins and roadbuilders. If a regular player tries breaking or placing a block on a road it should say "This is a road, you cannot break or place anything on it." in the chat

**Comment by lisacvuk** [comment]
That seems like a mess IMO. Are we sure we wanna go with areas? Perhaps one of the protector node mods would be a better fit, we could just define a custom protector node of 5x5x5 that allows everyone with roads priv to build.

**Comment by ChandlerBing1994** [comment]
Protector nodes are messy, no one wants to have several of them floating in the air to protect an area

**Comment by wrynvera** [comment]
Update on this. As per discussed with raven; preliminary 3 optional systems,  all dependent on areas protection API/exposed functions, will be implemented on server launch.
1. Grid-based protection blocks - disappear on use (to determine)
2. Markers like protection system (with more flexibility & disappear on use)
3. Flexible command protection as areas offer now

Since all systems uses the same protection system, there will no clashes between them.

See the #protection channel for further details. Other precise mechanics can be refined later, while providing a basic base system to use for now.

**Comment by wrynvera** [comment]
Issue discussion transferred to discord for consistency
